"""add followers_list_public to users

Revision ID: 581451ca4590
Revises: 8d9194b4cfdc
Create Date: 2026-05-05 19:01:00.985109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581451ca4590'
down_revision = '8d9194b4cfdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers_list_public', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('followers_list_public')

    # ### end Alembic commands ###
